Dictionary
0: bobble
1: bubble
2: bubbly
3: bubby
4: bumble
5: burble
6: burbly
7: cobble
8: cobbly
9: cobby
10: coble
11: gobble
12: gorble
13: hobble
14: jobble
Ordered Word Ladder Graph
V=15, E=22
<0 1> <0 7> <0 11> <0 13> <0 14> 
<1 0> <1 2> <1 4> <1 5> 
<2 1> <2 3> <2 6> 
<3 2> 
<4 1> <4 5> 
<5 1> <5 4> <5 6> 
<6 2> <6 5> 
<7 0> <7 8> <7 10> <7 11> <7 13> <7 14> 
<8 7> <8 9> 
<9 8> 
<10 7> 
<11 0> <11 7> <11 12> <11 13> <11 14> 
<12 11> 
<13 0> <13 7> <13 11> <13 14> 
<14 0> <14 7> <14 11> <14 13> 
Longest ladder length: 5
Longest ladders:
 1: bobble -> bubble -> bumble -> burble -> burbly
 2: bobble -> cobble -> gobble -> hobble -> jobble
