Dictionary
0: aaaaa
1: aaaab
2: aaaba
3: aaabb
4: aabaa
5: aabab
6: aabba
7: aabbb
8: abaaa
9: abaab
10: ababa
11: ababb
12: abbaa
13: abbab
14: abbba
15: abbbb
16: baaaa
17: baaab
18: baaba
19: baabb
20: babaa
21: babab
22: babba
23: babbb
24: bbaaa
25: bbaab
26: bbaba
27: bbabb
28: bbbaa
29: bbbab
30: bbbba
31: bbbbb
Ordered Word Ladder Graph
V=32, E=80
<0 1> <0 2> <0 4> <0 8> <0 16> 
<1 0> <1 3> <1 5> <1 9> <1 17> 
<2 0> <2 3> <2 6> <2 10> <2 18> 
<3 1> <3 2> <3 7> <3 11> <3 19> 
<4 0> <4 5> <4 6> <4 12> <4 20> 
<5 1> <5 4> <5 7> <5 13> <5 21> 
<6 2> <6 4> <6 7> <6 14> <6 22> 
<7 3> <7 5> <7 6> <7 15> <7 23> 
<8 0> <8 9> <8 10> <8 12> <8 24> 
<9 1> <9 8> <9 11> <9 13> <9 25> 
<10 2> <10 8> <10 11> <10 14> <10 26> 
<11 3> <11 9> <11 10> <11 15> <11 27> 
<12 4> <12 8> <12 13> <12 14> <12 28> 
<13 5> <13 9> <13 12> <13 15> <13 29> 
<14 6> <14 10> <14 12> <14 15> <14 30> 
<15 7> <15 11> <15 13> <15 14> <15 31> 
<16 0> <16 17> <16 18> <16 20> <16 24> 
<17 1> <17 16> <17 19> <17 21> <17 25> 
<18 2> <18 16> <18 19> <18 22> <18 26> 
<19 3> <19 17> <19 18> <19 23> <19 27> 
<20 4> <20 16> <20 21> <20 22> <20 28> 
<21 5> <21 17> <21 20> <21 23> <21 29> 
<22 6> <22 18> <22 20> <22 23> <22 30> 
<23 7> <23 19> <23 21> <23 22> <23 31> 
<24 8> <24 16> <24 25> <24 26> <24 28> 
<25 9> <25 17> <25 24> <25 27> <25 29> 
<26 10> <26 18> <26 24> <26 27> <26 30> 
<27 11> <27 19> <27 25> <27 26> <27 31> 
<28 12> <28 20> <28 24> <28 29> <28 30> 
<29 13> <29 21> <29 25> <29 28> <29 31> 
<30 14> <30 22> <30 26> <30 28> <30 31> 
<31 15> <31 23> <31 27> <31 29> <31 30> 
Longest ladder length: 6
Longest ladders:
 1: aaaaa -> aaaab -> aaabb -> aabbb -> abbbb -> bbbbb
 2: aaaaa -> aaaab -> aaabb -> aabbb -> babbb -> bbbbb
 3: aaaaa -> aaaab -> aaabb -> ababb -> abbbb -> bbbbb
 4: aaaaa -> aaaab -> aaabb -> ababb -> bbabb -> bbbbb
 5: aaaaa -> aaaab -> aaabb -> baabb -> babbb -> bbbbb
 6: aaaaa -> aaaab -> aaabb -> baabb -> bbabb -> bbbbb
 7: aaaaa -> aaaab -> aabab -> aabbb -> abbbb -> bbbbb
 8: aaaaa -> aaaab -> aabab -> aabbb -> babbb -> bbbbb
 9: aaaaa -> aaaab -> aabab -> abbab -> abbbb -> bbbbb
10: aaaaa -> aaaab -> aabab -> abbab -> bbbab -> bbbbb
11: aaaaa -> aaaab -> aabab -> babab -> babbb -> bbbbb
12: aaaaa -> aaaab -> aabab -> babab -> bbbab -> bbbbb
13: aaaaa -> aaaab -> abaab -> ababb -> abbbb -> bbbbb
14: aaaaa -> aaaab -> abaab -> ababb -> bbabb -> bbbbb
15: aaaaa -> aaaab -> abaab -> abbab -> abbbb -> bbbbb
16: aaaaa -> aaaab -> abaab -> abbab -> bbbab -> bbbbb
17: aaaaa -> aaaab -> abaab -> bbaab -> bbabb -> bbbbb
18: aaaaa -> aaaab -> abaab -> bbaab -> bbbab -> bbbbb
19: aaaaa -> aaaab -> baaab -> baabb -> babbb -> bbbbb
20: aaaaa -> aaaab -> baaab -> baabb -> bbabb -> bbbbb
21: aaaaa -> aaaab -> baaab -> babab -> babbb -> bbbbb
22: aaaaa -> aaaab -> baaab -> babab -> bbbab -> bbbbb
23: aaaaa -> aaaab -> baaab -> bbaab -> bbabb -> bbbbb
24: aaaaa -> aaaab -> baaab -> bbaab -> bbbab -> bbbbb
25: aaaaa -> aaaba -> aaabb -> aabbb -> abbbb -> bbbbb
26: aaaaa -> aaaba -> aaabb -> aabbb -> babbb -> bbbbb
27: aaaaa -> aaaba -> aaabb -> ababb -> abbbb -> bbbbb
28: aaaaa -> aaaba -> aaabb -> ababb -> bbabb -> bbbbb
29: aaaaa -> aaaba -> aaabb -> baabb -> babbb -> bbbbb
30: aaaaa -> aaaba -> aaabb -> baabb -> bbabb -> bbbbb
31: aaaaa -> aaaba -> aabba -> aabbb -> abbbb -> bbbbb
32: aaaaa -> aaaba -> aabba -> aabbb -> babbb -> bbbbb
33: aaaaa -> aaaba -> aabba -> abbba -> abbbb -> bbbbb
34: aaaaa -> aaaba -> aabba -> abbba -> bbbba -> bbbbb
35: aaaaa -> aaaba -> aabba -> babba -> babbb -> bbbbb
36: aaaaa -> aaaba -> aabba -> babba -> bbbba -> bbbbb
37: aaaaa -> aaaba -> ababa -> ababb -> abbbb -> bbbbb
38: aaaaa -> aaaba -> ababa -> ababb -> bbabb -> bbbbb
39: aaaaa -> aaaba -> ababa -> abbba -> abbbb -> bbbbb
40: aaaaa -> aaaba -> ababa -> abbba -> bbbba -> bbbbb
41: aaaaa -> aaaba -> ababa -> bbaba -> bbabb -> bbbbb
42: aaaaa -> aaaba -> ababa -> bbaba -> bbbba -> bbbbb
43: aaaaa -> aaaba -> baaba -> baabb -> babbb -> bbbbb
44: aaaaa -> aaaba -> baaba -> baabb -> bbabb -> bbbbb
45: aaaaa -> aaaba -> baaba -> babba -> babbb -> bbbbb
46: aaaaa -> aaaba -> baaba -> babba -> bbbba -> bbbbb
47: aaaaa -> aaaba -> baaba -> bbaba -> bbabb -> bbbbb
48: aaaaa -> aaaba -> baaba -> bbaba -> bbbba -> bbbbb
49: aaaaa -> aabaa -> aabab -> aabbb -> abbbb -> bbbbb
50: aaaaa -> aabaa -> aabab -> aabbb -> babbb -> bbbbb
51: aaaaa -> aabaa -> aabab -> abbab -> abbbb -> bbbbb
52: aaaaa -> aabaa -> aabab -> abbab -> bbbab -> bbbbb
53: aaaaa -> aabaa -> aabab -> babab -> babbb -> bbbbb
54: aaaaa -> aabaa -> aabab -> babab -> bbbab -> bbbbb
55: aaaaa -> aabaa -> aabba -> aabbb -> abbbb -> bbbbb
56: aaaaa -> aabaa -> aabba -> aabbb -> babbb -> bbbbb
57: aaaaa -> aabaa -> aabba -> abbba -> abbbb -> bbbbb
58: aaaaa -> aabaa -> aabba -> abbba -> bbbba -> bbbbb
59: aaaaa -> aabaa -> aabba -> babba -> babbb -> bbbbb
60: aaaaa -> aabaa -> aabba -> babba -> bbbba -> bbbbb
61: aaaaa -> aabaa -> abbaa -> abbab -> abbbb -> bbbbb
62: aaaaa -> aabaa -> abbaa -> abbab -> bbbab -> bbbbb
63: aaaaa -> aabaa -> abbaa -> abbba -> abbbb -> bbbbb
64: aaaaa -> aabaa -> abbaa -> abbba -> bbbba -> bbbbb
65: aaaaa -> aabaa -> abbaa -> bbbaa -> bbbab -> bbbbb
66: aaaaa -> aabaa -> abbaa -> bbbaa -> bbbba -> bbbbb
67: aaaaa -> aabaa -> babaa -> babab -> babbb -> bbbbb
68: aaaaa -> aabaa -> babaa -> babab -> bbbab -> bbbbb
69: aaaaa -> aabaa -> babaa -> babba -> babbb -> bbbbb
70: aaaaa -> aabaa -> babaa -> babba -> bbbba -> bbbbb
71: aaaaa -> aabaa -> babaa -> bbbaa -> bbbab -> bbbbb
72: aaaaa -> aabaa -> babaa -> bbbaa -> bbbba -> bbbbb
73: aaaaa -> abaaa -> abaab -> ababb -> abbbb -> bbbbb
74: aaaaa -> abaaa -> abaab -> ababb -> bbabb -> bbbbb
75: aaaaa -> abaaa -> abaab -> abbab -> abbbb -> bbbbb
76: aaaaa -> abaaa -> abaab -> abbab -> bbbab -> bbbbb
77: aaaaa -> abaaa -> abaab -> bbaab -> bbabb -> bbbbb
78: aaaaa -> abaaa -> abaab -> bbaab -> bbbab -> bbbbb
79: aaaaa -> abaaa -> ababa -> ababb -> abbbb -> bbbbb
80: aaaaa -> abaaa -> ababa -> ababb -> bbabb -> bbbbb
81: aaaaa -> abaaa -> ababa -> abbba -> abbbb -> bbbbb
82: aaaaa -> abaaa -> ababa -> abbba -> bbbba -> bbbbb
83: aaaaa -> abaaa -> ababa -> bbaba -> bbabb -> bbbbb
84: aaaaa -> abaaa -> ababa -> bbaba -> bbbba -> bbbbb
85: aaaaa -> abaaa -> abbaa -> abbab -> abbbb -> bbbbb
86: aaaaa -> abaaa -> abbaa -> abbab -> bbbab -> bbbbb
87: aaaaa -> abaaa -> abbaa -> abbba -> abbbb -> bbbbb
88: aaaaa -> abaaa -> abbaa -> abbba -> bbbba -> bbbbb
89: aaaaa -> abaaa -> abbaa -> bbbaa -> bbbab -> bbbbb
90: aaaaa -> abaaa -> abbaa -> bbbaa -> bbbba -> bbbbb
91: aaaaa -> abaaa -> bbaaa -> bbaab -> bbabb -> bbbbb
92: aaaaa -> abaaa -> bbaaa -> bbaab -> bbbab -> bbbbb
93: aaaaa -> abaaa -> bbaaa -> bbaba -> bbabb -> bbbbb
94: aaaaa -> abaaa -> bbaaa -> bbaba -> bbbba -> bbbbb
95: aaaaa -> abaaa -> bbaaa -> bbbaa -> bbbab -> bbbbb
96: aaaaa -> abaaa -> bbaaa -> bbbaa -> bbbba -> bbbbb
97: aaaaa -> baaaa -> baaab -> baabb -> babbb -> bbbbb
98: aaaaa -> baaaa -> baaab -> baabb -> bbabb -> bbbbb
99: aaaaa -> baaaa -> baaab -> babab -> babbb -> bbbbb
