Dictionary
0: arkose
1: arose
2: arouse
3: arse
4: arses
5: arsis
6: assis
7: assise
8: assish
9: assist
10: brose
11: brosy
12: browse
13: browst
14: crouse
15: croute
16: cruse
17: crush
18: crust
19: crusta
20: crusty
21: cruth
22: cush
23: cushy
24: cusk
25: cusp
26: drowse
27: drowsy
28: frowst
29: growse
30: prosy
31: proxy
32: route
33: router
34: roxy
35: rust
36: ruth
37: souter
38: touter
39: truth
Ordered Word Ladder Graph
V=40, E=48
<0 1> 
<1 0> <1 2> <1 3> <1 10> 
<2 1> <2 14> 
<3 1> <3 4> 
<4 3> <4 5> 
<5 4> <5 6> 
<6 5> <6 7> <6 8> <6 9> 
<7 6> <7 8> <7 9> 
<8 6> <8 7> <8 9> 
<9 6> <9 7> <9 8> 
<10 1> <10 11> <10 12> 
<11 10> <11 30> 
<12 10> <12 13> <12 26> <12 29> 
<13 12> <13 28> 
<14 2> <14 15> <14 16> 
<15 14> <15 32> 
<16 14> <16 17> <16 18> 
<17 16> <17 18> <17 21> <17 22> 
<18 16> <18 17> <18 19> <18 20> <18 35> 
<19 18> <19 20> 
<20 18> <20 19> 
<21 17> <21 36> <21 39> 
<22 17> <22 23> <22 24> <22 25> 
<23 22> 
<24 22> <24 25> 
<25 22> <25 24> 
<26 12> <26 27> <26 29> 
<27 26> 
<28 13> 
<29 12> <29 26> 
<30 11> <30 31> 
<31 30> <31 34> 
<32 15> <32 33> 
<33 32> <33 37> <33 38> 
<34 31> 
<35 18> 
<36 21> <36 39> 
<37 33> <37 38> 
<38 33> <38 37> 
<39 21> <39 36> 
Longest ladder length: 9
Longest ladders:
 1: arkose -> arose -> arouse -> crouse -> croute -> route -> router -> souter -> touter
 2: arkose -> arose -> arouse -> crouse -> cruse -> crush -> crust -> crusta -> crusty
 3: arkose -> arose -> arouse -> crouse -> cruse -> crush -> cruth -> ruth -> truth
 4: arkose -> arose -> arouse -> crouse -> cruse -> crush -> cush -> cusk -> cusp
 5: arkose -> arose -> arse -> arses -> arsis -> assis -> assise -> assish -> assist
